---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-deploy-2-bad-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  wait: true
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy-2
