apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-5yy1td
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-5yy1td
      namespace: flux-system
  timeout: 2m

