---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour
  namespace: contour
spec:
  healthChecks:
  - kind: Deployment
    name: contour
    namespace: projectcontour
  - kind: DaemonSet
    name: envoy
    namespace: projectcontour
  interval: 10m0s
  path: ./examples/contour
  prune: true
  sourceRef:
    kind: GitRepository
    name: contour
  timeout: 3m0s
