---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    serverTLS:
      enabled: true
      secretName: "my-tls-secret"
    image:
      tag: v0.8.1-rc.4
      repository: ghcr.io/weaveworks/wego-app
    adminUser:
      create: true
      passwordHash: $2a$10$AXQbmU9BwY4zqQPIe/D3ruRA.vM5RCGo/TOiMU5yPQnJYU8D4meoa
      username: IAdmin12
      rbac:
        create: true

