# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: weave-gitops-app
# spec:
#   releaseName: weave-gitops-app
#   targetNamespace: flux-system
#   chart:
#     spec:
#       chart: charts/gitops-server
#       sourceRef:
#         kind: GitRepository
#         name: weave-gitops
#         namespace: flux-system
#       version: "1.0.0"
#   interval: 10m0s
#   install:
#     remediation:
#       retries: 3
#   values:
#     image:
#       # FIXME gitops-server -> weave-gitops-app
#       repository: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops/gitops-server # {"$imagepolicy": "flux-system:weave-gitops-app:name"}
#       tag: 1650651383-99d7927aca4166817e407a69cf78f0da2ebe41ca # {"$imagepolicy": "flux-system:weave-gitops-app:tag"}
#     adminUser:
#       create: true
#       username: meself
#       password: moi
#     # FIXME? handle TLS @ that LB?
#     additionalArgs: ["--insecure"]
#     service:
#       annotations:
#         beta.cloud.google.com/backend-config: '{"default": "default-lb-backend-config"}'
#         networking.gke.io/v1beta1.FrontendConfig: default-lb-frontend-config
#     # Enable ingress (we don't set a type b/c GKE magics that)
#     ingress:
#       enabled: true
#       annotations:
#         networking.gke.io/managed-certificates: gitops-cert # must match name tls-certs.yaml
#       hosts:
#       - host: gitops.euw1.wego-gke.weave.works
#         paths:
#         - path: /*
#           pathType: ImplementationSpecific # ImplementationSpecific => let the lb decide

# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: ww-gitops
#   namespace: flux-system
# spec:
#   chart:
#     spec:
#       chart: weave-gitops
#       sourceRef:
#         kind: HelmRepository
#         name: ww-gitops
#   interval: 1m0s
#   values:
#     adminUser:
#       create: true
#       password: moi
#       username: meself
#     namespace: flux-system
#     rbac:
#       create: true

# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: ww-gitops
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   url: https://helm.gitops.weave.works


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  releaseName: gitops-server
  targetNamespace: flux-system
  chart:
    spec:
      chart: ./charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: ww-gitops
  install:
    remediation:
      retries: 3
  values:
    namespace: flux-system
    additionalArgs: ["--insecure"]
    image:
      tag: v0.7.1-rc2
      repository: ghcr.io/weaveworks/wego-app
    adminUser:
      create: true
      username: myself
      password: unsecure
  interval: 1m0s

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/weaveworks/weave-gitops
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
