apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-release-loki-0
  namespace: default
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: HelmRepository
    name: loki
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: my-release-loki-0
      namespace: default
  timeout: 2m

