apiVersion: v1
kind: Service
metadata:
  name: firefly-service
  namespace: firefly
  labels:
    app: firefly-app
spec:
  type: LoadBalancer
  selector: 
    app: firefly-app
  ports: 
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
